function TrafficModule({indices,buckets,grain,primaryColor}){
 const model=window.UNIFIED_REPORT;
 const total=React.useMemo(()=>model.aggregate(indices),[indices]);
 const [picked,setPicked]=React.useState(null),[expanded,setExpanded]=React.useState(new Set()),[notice,setNotice]=React.useState('');
 React.useEffect(()=>{setPicked(null);setExpanded(new Set())},[indices,grain]);
 const rows=React.useMemo(()=>buckets.map(b=>({...b,...model.aggregate(b.indices)})),[buckets]);
 const selected=picked&&picked.indices.every(i=>indices.includes(i))?picked:null,current=selected||total;
 const flat=rows.flatMap(r=>grain==='week'&&expanded.has(r.key)?[r,...r.indices.map(i=>({...groups([i],'day')[0],...model.aggregate([i]),child:true}))]:[r]);
 const pct=(n,d)=>d?(100*n/d).toFixed(2)+'%':'—',ref=React.useRef(null);
 React.useEffect(()=>{
  const chart=echarts.init(ref.current);
  chart.setOption({animation:false,tooltip:{trigger:'item',formatter:p=>`${p.name}：${fmt(p.data.actualCount)} ${p.data.unit}`},series:[{type:'funnel',sort:'none',left:'10%',width:'80%',top:18,bottom:18,min:0,max:100,minSize:'20%',maxSize:'100%',gap:8,label:{show:true,position:'inside',fontSize:13,lineHeight:22,formatter:p=>`${p.name}\n${fmt(p.data.actualCount)} ${p.data.unit}`},labelLine:{show:false},itemStyle:{borderWidth:0},data:[['浏览量 PV',current.pv],['访客数 UV',current.uv],['完成注册',current.registered],['完成实名',current.verified],['发生消费',current.consumption]].map(([name,actualCount],i)=>({name,actualCount,unit:i===0?'次':'人',value:[100,80,60,40,20][i],itemStyle:{color:[primaryColor,'#299E94','#298E87','#247477','#174A5B'][i]}}))}]});
  const resize=()=>chart.resize();window.addEventListener('resize',resize);return()=>{chart.dispose();window.removeEventListener('resize',resize)};
 },[current,primaryColor]);
 const fields=[['pv','网站 PV'],['uv','网站 UV'],['registered','注册总量'],['verified','实名量'],['consumption','消费量']];
 function csv(){const values=r=>[r.label,dates[r.indices[0]],dates[r.indices.at(-1)],...fields.map(([k])=>r[k]),pct(r.registered,r.uv)];const data=[['时间','开始日期','结束日期',...fields.map(f=>f[1]),'注册/UV'],values({...total,label:'区间合计',indices}),...flat.map(values)];const url=URL.createObjectURL(new Blob(['\uFEFF'+data.map(r=>r.join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`访问转化-${dates[indices[0]]}-${dates[indices.at(-1)]}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('已导出当前日期范围的数据')}
 return <section className="traffic-panel unified-report" aria-label="访问与转化报告"><div className="section-head"><div><div className="traffic-title"><h2>访问与转化报告</h2><span className="badge">统一联动 · 模拟明细</span></div><p className="report-active-range">{dates[indices[0]]} 至 {dates[indices.at(-1)]} · {indices.length} 天 · {grain==='day'?'按日':'按周'} · 跟随顶部日期筛选</p></div><button onClick={csv}>导出访问数据 ↓</button></div>
 <div className="traffic-kpis">{[['pv','浏览量 PV','次'],['uv','访客数 UV','人'],['registered','注册总量','人'],['verified','实名量','人']].map(([k,label,unit])=><div className="traffic-kpi" key={k}><span>{label}</span><strong>{fmt(total[k])}<small>{unit}</small></strong><p>{k==='pv'?'所选日期内求和':k==='uv'?'所选日期段跨天去重':'所选日期段模拟人数'}</p></div>)}</div>
 <div className="funnel-heading"><div><h3>PV → UV → 注册 → 实名 → 消费</h3><p>{selected?`${selected.label} · ${short(dates[selected.indices[0]])}—${short(dates[selected.indices.at(-1)])}`:'整个所选日期段'} · 模拟用户转化漏斗</p></div>{selected?<button onClick={()=>setPicked(null)}>返回整个区间</button>:<span>点击下方日期或周次查看对应漏斗</span>}</div>
 <div className="funnel-layout"><div ref={ref} className="traffic-funnel report-funnel"></div><div className="funnel-details">{[['UV → 注册',current.registered,current.uv],['注册 → 实名',current.verified,current.registered],['实名 → 消费',current.consumption,current.verified]].map(([label,n,d])=><div key={label}><span>{label} · 模拟转化率</span><strong>{pct(n,d)}</strong><small>{fmt(n)} / {fmt(d)} 人</small></div>)}<p className="report-ratio-note">PV 为浏览次数，UV 为去重访客。人均浏览 {(current.pv/current.uv).toFixed(2)} 页 · 消费用户 {fmt(current.consumption)} 人。漏斗按固定层级逐级收窄，人数与转化率随所选日期更新。</p></div></div>
 <div className="traffic-table-title"><h3>访问转化{grain==='day'?'日报':'周报'}</h3><span>{grain==='week'?'点击 + 展开每天，点击周次切换漏斗':'每天一行，点击日期切换漏斗'}</span></div>
 <div className="traffic-scroll"><table className="traffic-table"><thead><tr><th>时间范围</th>{fields.map(([k,label])=><th key={k}>{label}<small>{k==='pv'?'次 · SUM':k==='uv'?'人 · 区间去重':'人 · 模拟'}</small></th>)}<th>注册 / UV<small>模拟转化率</small></th></tr></thead><tbody><tr className="traffic-summary"><th>区间合计<small>{indices.length} 天</small></th>{fields.map(([k])=><td key={k}>{fmt(total[k])}</td>)}<td>{pct(total.registered,total.uv)}</td></tr>{flat.map((r,i)=><tr key={r.key+'-'+i} className={`${r.child?'traffic-child':''} ${selected===r?'selected':''}`}><th>{grain==='week'&&!r.child?<button className="traffic-week-expand" aria-label={`${expanded.has(r.key)?'收起':'展开'}访问${r.label}`} aria-expanded={expanded.has(r.key)} onClick={()=>setExpanded(new Set(expanded.has(r.key)?[...expanded].filter(k=>k!==r.key):[...expanded,r.key]))}>{expanded.has(r.key)?'−':'+'}</button>:null}<button className="traffic-period" onClick={()=>setPicked(r)}>{r.label}</button>{grain==='week'&&!r.child?<small>{short(dates[r.indices[0]])}—{short(dates[r.indices.at(-1)])}{r.partial?` · ${r.indices.length} 天`:''}</small>:null}</th>{fields.map(([k])=><td key={k}>{fmt(r[k])}</td>)}<td>{pct(r.registered,r.uv)}</td></tr>)}</tbody></table></div>
 <div className="traffic-note">数据覆盖 2026/07/01—09/10（含首尾日期），按北京时间统计。PV 按日求和；UV 按模拟用户标识跨天、跨周去重，不能直接累加每天 UV。顶部分类注册合计与本模块注册总量一致。</div>
 <div className="traffic-note secondary">8/10—9/6 的四个完整周，PV、UV、注册、实名、消费的周值与附件一致；每日分配、跨周访客重合及其他日期均为构造数据。为演示完整漏斗，实名和消费暂按用户人数模拟，并假设附件年份为 2026；不代表已验证的真实转化口径。上方分类明细亦为模拟拆分。{notice?<span role="status"> {notice}</span>:null}</div>
 </section>
}
